### ISSUE TITLE
Hangs when Configuring SSH

### ISSUE THREAD

**Issue by gangster** [awvessel/vessel#19]
Hi there.   Trying to get up and going with Vessel, and when I go to build the environment, the app seems to hang on the configuring ssh step.  Also, I can't abort the action.  I have to close out altogether and restart Vessel to do anything else.  Anyway, 

Not exactly sure how to troubleshoot this, so some guidance would be much appreciated.   

My manifest is here:  https://github.com/gangster/manifest/blob/master/manifest.yaml

- OS X 10.10
- VirtualBox 4.3.16
- Vagrant 1.6.5

Thanks for the help!

![screen shot 2014-09-11 at 11 08 41 am](https://cloud.githubusercontent.com/assets/4863/4236239/b8f2c41e-39c5-11e4-8732-e93743f19726.png)

**Comment by gmr** [comment]
SSH has now been removed in 0.3.1, since docker exec is now supported.
